# Generated by Django 4.1.7 on 2023-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='VIN',
            field=models.CharField(max_length=100, verbose_name='VIN'),
        ),
    ]
