# Generated by Django 4.1.7 on 2023-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy', '0002_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type_of_drive',
            field=models.CharField(choices=[('AWD', 'AWD'), ('FWD', 'FWD'), ('RWD', 'RWD')], max_length=3, verbose_name='Type of drive'),
        ),
    ]
