# Generated by Django 4.1.7 on 2023-06-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy', '0004_alter_client_credit_card_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit_card_CVV',
            field=models.CharField(max_length=3, verbose_name='Credit card CVV'),
        ),
    ]
